language: python

# module will be tested with all listed python version
python:
  - "3.6"

# command to install dependencies
cache: pip
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run --source='.' -m unittest discover tests "*_test.py"
  - coverage report -m --omit="tests/*","setup.py","*/__init__.py","env/*" --fail-under=90

# module will be tested only on listed branches
branches:
  only:
    - master
